// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.20.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class Error with _$Error implements FrbException {
  const factory Error.runtimeNotInitialized() = Error_RuntimeNotInitialized;
  const factory Error.classLoader() = Error_ClassLoader;
  const factory Error.runtime() = Error_Runtime;
  const factory Error.javaVm() = Error_JavaVM;
  const factory Error.txAlreadySet() = Error_TxAlreadySet;
  const factory Error.txNotInitialized() = Error_TxNotInitialized;
  const factory Error.unknownPeripheral(
    String field0,
  ) = Error_UnknownPeripheral;
}
