// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.64.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

abstract class Btleplug {
  Stream<String> init({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitConstMeta;

  Stream<String> bleScan({required List<String> filter, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBleScanConstMeta;

  Future<void> bleStopScan({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBleStopScanConstMeta;
}

class BtleplugImpl implements Btleplug {
  final BtleplugPlatform _platform;
  factory BtleplugImpl(ExternalLibrary dylib) =>
      BtleplugImpl.raw(BtleplugPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory BtleplugImpl.wasm(FutureOr<WasmModule> module) =>
      BtleplugImpl(module as ExternalLibrary);
  BtleplugImpl.raw(this._platform);
  Stream<String> init({dynamic hint}) {
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_init(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kInitConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kInitConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "init",
        argNames: [],
      );

  Stream<String> bleScan({required List<String> filter, dynamic hint}) {
    var arg0 = _platform.api2wire_StringList(filter);
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ble_scan(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kBleScanConstMeta,
      argValues: [filter],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleScanConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble_scan",
        argNames: ["filter"],
      );

  Future<void> bleStopScan({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ble_stop_scan(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kBleStopScanConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleStopScanConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble_stop_scan",
        argNames: [],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
